apiVersion: apps/v1
# kind: Deployment | define a group of pods which can be scaled
kind: Deployment
metadata:
  name: spark-etl-sample
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark
  template:
    metadata:
      labels:
        app: spark
    spec:
      containers:
        - name: spark-etl-sample
          image: spark-etl-sample
          imagePullPolicy: Never
---
# Simply a service to route traffic into the deployment pods
apiVersion: v1
kind: Service
metadata:
  name: spark-etl-sample
  namespace: default
spec:
  type: NodePort
  selector:
    app: spark
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30001
